# @package envs
env_configs:
  carla_map: [Town01, Town02, Town03, Town04, Town05]
  num_zombie_vehicles: [0, 20]
  num_zombie_walkers: [0, 20]
  weather_group: dynamic_1.0
  target_speed: 10
env_id: Endless-v0
gpu: [0]
