defaults:
  - agent: collector
  - envs: endless_all
actors:
  hero:
    agent: collector
    reward:
      entry_point: reward.valeo_action:ValeoAction
      kwargs: {}
    terminal:
      entry_point: terminal.valeo_no_det_px:ValeoNoDetPx
      kwargs: {}
ev_id: hero
carla_sh_path: /home/bokai/Documents/Carla/CarlaUE4.sh
kill_running: true
dummy: false
