_BASE_: ../default.yaml
PROJECT_DIR: classifier_guidance_result
TRAIN:
  USE_COND: CLASSIFIER_GUIDANCE
GUIDANCE:
  USE_COND: CLASSIFIER_GUIDANCE
  CLASSIFIER_SCALE: 15.0
  LOSS_LIST:
  -
    - TargetGuidance
    - []